### ISSUE TITLE
Backpack model not showing on player in 1.21.4

### ISSUE THREAD

**Issue by arthurkenzo** [Stein-N/Resource-Backpacks#28] opened 2024-12-12 02:38 UTC
### Mod loader

Fabric

### Mod version

0.10.2-BETA

### Minecraft version

1.21.4

### Issue description

Backpack doesn't appear on the player's back when put on the chest armor slot. I can still interact with the backpack, but I can't see it when in F5. The backpack renders fine when I place it on the ground or in my hand. 

### If Bug

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Provide the latest.log file

https://gist.github.com/arthurkenzo/9cffdb4d6c0325e6a152593f967cad75

**Comment by arthurkenzo** [comment] 2024-12-12 03:21
I noticed that the mod version in the log file is 0.10.1-BETA, apparently when I download the mod through the Modrinth app the interface says 0.10.2 but the file that gets installed is 0.10.1. In any case, I tested it with 0.10.2 from CurseForge and the problem persists.

**Comment by arthurkenzo** [comment] 2024-12-16 14:46
In case these commits haven't already solved the problem: I saw in another mod's Modrinth page (https://modrinth.com/datapack/vanilla-backpacks) that due to some changes to the item models in 1.21.4 their mod update was taking longer. Maybe they're having similar issues with the rendering of the backpack on the player?

**Comment by Stein-N** [comment] 2024-12-16 15:01
Hey the problem is fixed now and will be shipped with the next update, eventually today already, but i have to clean the code a little bit before that.

**Comment by Stein-N** [comment] 2024-12-16 15:34
New version is uploaded to Modrinth and Curseforge.

**Closed as completed by Stein-N** 2024-12-16 15:34 UTC
Labels: 1.21, ready for next Update

**Comment by arthurkenzo** [comment] 2024-12-16 15:36
Ah nice! Thanks very much : )
